In [1]:
#进行数据集的分片
import warnings
warnings.filterwarnings('ignore')

import csv
import pandas as pd
import time

In [5]:
begin_time = time.time()
print(f'Begin Time : {time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(begin_time))}')

file = './out_put/encode_data.csv'
df = pd.read_csv(file, index_col = 0)

end_time = time.time()
print(f'End Time : {time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(end_time))}')

Begin Time : 2020-02-01 15:42:12
End Time : 2020-02-01 15:42:14

In [21]:
#对编码之后的数据进行分片
begin_time = time.time()
print(f'Begin Time : {time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(begin_time))}')

#将数据分为train/validata/testdata三部分
df_1 = df[df['click'] == 1]
df_0 = df[df['click'] == 0]

df_1_test =df_1.sample(frac=0.3, random_state=100)
df_0_test =df_0.sample(frac=0.3, random_state=100)

df_1_other = df_1[~df_1.index.isin(df_1_test.index)]
df_0_other = df_0[~df_0.index.isin(df_0_test.index)]

df_1_vali = df_1_other.sample(frac=0.2, random_state=100)
df_0_vali = df_0_other.sample(frac=0.2, random_state=100)

df_1_train = df_1_other[~df_1_other.index.isin(df_1_vali.index)]
df_0_train = df_0_other[~df_0_other.index.isin(df_0_vali.index)]

#合并1/0
df_train = pd.concat([df_1_train,df_0_train], ignore_index=True)
df_vali = pd.concat([df_1_vali,df_0_vali], ignore_index=True)
df_test = pd.concat([df_1_test,df_0_test], ignore_index=True)

print(f'--split data : {time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time()))}')

nums_train = df_train['click'].count()
nums_vali = df_train['click'].count()
nums_test = df_train['click'].count()

print(f'--split rate train VS vali VS test: {nums_train}:{nums_vali}:{nums_test}')

df_train.to_csv('./out_put/encode_data_train.csv')
df_train.to_csv('./out_put/encode_data_train.csv')
df_train.to_csv('./out_put/encode_data_train.csv')

end_time = time.time()
print(f'End Time : {time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(end_time))}')

Begin Time : 2020-02-01 15:54:53
End Time : 2020-02-01 15:54:54

In [20]:
df_1_other.head()

,click,banner_pos,device_type,device_conn_type,C1,C14,C15,C16,C17,C18,...,C21,site_id_enconde,site_domain_enconde,site_category_enconde,app_id_enconde,app_domain_enconde,app_category_enconde,device_id_enconde,device_ip_enconde,device_model_enconde
8,1,0,1,2,1005,15707,320,50,1722,0,...,79,260,1927,2,2127,73,0,55297,67996,1684
23,1,0,1,0,1005,15701,320,50,1722,0,...,79,260,1927,2,2127,73,0,55297,242399,2278
27,1,0,1,0,1005,21611,320,50,2480,3,...,61,1110,1568,6,789,22,3,50522,51233,4233
32,1,0,1,0,1005,15708,320,50,1722,0,...,79,260,1927,2,2127,73,0,55297,200821,1471
37,1,0,1,0,1005,18993,320,50,2161,0,...,157,1110,1568,6,100,41,21,55297,252321,804

In [14]:
df_1.head()

,click,banner_pos,device_type,device_conn_type,C1,C14,C15,C16,C17,C18,...,C21,site_id_enconde,site_domain_enconde,site_category_enconde,app_id_enconde,app_domain_enconde,app_category_enconde,device_id_enconde,device_ip_enconde,device_model_enconde
8,1,0,1,2,1005,15707,320,50,1722,0,...,79,260,1927,2,2127,73,0,55297,67996,1684
23,1,0,1,0,1005,15701,320,50,1722,0,...,79,260,1927,2,2127,73,0,55297,242399,2278
27,1,0,1,0,1005,21611,320,50,2480,3,...,61,1110,1568,6,789,22,3,50522,51233,4233
32,1,0,1,0,1005,15708,320,50,1722,0,...,79,260,1927,2,2127,73,0,55297,200821,1471
37,1,0,1,0,1005,18993,320,50,2161,0,...,157,1110,1568,6,100,41,21,55297,252321,804