In [2]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

In [3]:
file = './data/train_subset_1000000.csv'
df = pd.read_csv(file)

In [8]:
print(f'--All data:{df.id.count()}')
y_1_nums = df[df["click"] == 1].id.count()
y_0_nums = df[df["click"] == 0].id.count()
print(f'--1 data:{y_1_nums}')
print(f'--0 data:{y_0_nums}')
print(f'--0 VS 1 => {round(y_0_nums/y_1_nums,2)}:1')

--All data:999999
--1 data:160219
--0 data:839780
--0 VS 1 => 5.24:1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 0 to 999998
Data columns (total 24 columns):
id                  999999 non-null float64
click               999999 non-null int64
hour                999999 non-null int64
C1                  999999 non-null int64
banner_pos          999999 non-null int64
site_id             999999 non-null object
site_domain         999999 non-null object
site_category       999999 non-null object
app_id              999999 non-null object
app_domain          999999 non-null object
app_category        999999 non-null object
device_id           999999 non-null object
device_ip           999999 non-null object
device_model        999999 non-null object
device_type         999999 non-null int64
device_conn_type    999999 non-null int64
C14                 999999 non-null int64
C15                 999999 non-null int64
C16                 999999 non-null int64
C17                 999999 non-null int64
C18                 999999 non-null int64
C19                 999999 non-null int64
C20                 999999 non-null int64
C21                 999999 non-null int64
dtypes: float64(1), int64(14), object(9)
memory usage: 183.1+ MB

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 0 to 999998
Data columns (total 24 columns):
id                  999999 non-null float64
click               999999 non-null int64
hour                999999 non-null int64
C1                  999999 non-null int64
banner_pos          999999 non-null int64
site_id             999999 non-null object
site_domain         999999 non-null object
site_category       999999 non-null object
app_id              999999 non-null object
app_domain          999999 non-null object
app_category        999999 non-null object
device_id           999999 non-null object
device_ip           999999 non-null object
device_model        999999 non-null object
device_type         999999 non-null int64
device_conn_type    999999 non-null int64
C14                 999999 non-null int64
C15                 999999 non-null int64
C16                 999999 non-null int64
C17                 999999 non-null int64
C18                 999999 non-null int64
C19                 999999 non-null int64
C20                 999999 non-null int64
C21                 999999 non-null int64
dtypes: float64(1), int64(14), object(9)
memory usage: 183.1+ MB

In [14]:
df[["id","click","app_id","app_domain","app_category","device_id","device_ip","device_model"]].head()

,id,click,app_id,app_domain,app_category,device_id,device_ip,device_model
0,1.000009e+18,0,ecad2386,7801e8d9,07d7df22,a99f214a,ddd2926e,44956a24
1,1.000017e+19,0,ecad2386,7801e8d9,07d7df22,a99f214a,96809ac8,711ee120
2,1.000037e+19,0,ecad2386,7801e8d9,07d7df22,a99f214a,b3cf8def,8a4875bd
3,1.000064e+19,0,ecad2386,7801e8d9,07d7df22,a99f214a,e8275b8f,6332421a
4,1.000068e+19,0,ecad2386,7801e8d9,07d7df22,a99f214a,9644d0bf,779d90c2

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,999999.0,9.376309e+18,5.236908e+18,9.984920e+12,4.846660e+18,9.834382e+18,1.373053e+19,1.844670e+19
click,999999.0,1.602192e-01,3.668094e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
hour,999999.0,1.410210e+07,1.493255e+00,1.410210e+07,1.410210e+07,1.410210e+07,1.410210e+07,1.410210e+07
C1,999999.0,1.005088e+03,1.156928e+00,1.001000e+03,1.005000e+03,1.005000e+03,1.005000e+03,1.012000e+03
banner_pos,999999.0,2.299222e-01,4.646270e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00
device_type,999999.0,1.025540e+00,4.538988e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.000000e+00
device_conn_type,999999.0,2.233602e-01,6.671590e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
C14,999999.0,1.826220e+04,3.510366e+03,3.750000e+02,1.570700e+04,1.925100e+04,2.115300e+04,2.170500e+04
C15,999999.0,3.189658e+02,1.945291e+01,1.200000e+02,3.200000e+02,3.200000e+02,3.200000e+02,1.024000e+03
C16,999999.0,5.649555e+01,3.654696e+01,2.000000e+01,5.000000e+01,5.000000e+01,5.000000e+01,1.024000e+03
C17,999999.0,2.041031e+03,4.412010e+02,1.120000e+02,1.722000e+03,2.161000e+03,2.420000e+03,2.497000e+03
C18,999999.0,1.452260e+00,1.362637e+00,0.000000e+00,0.000000e+00,1.000000e+00,3.000000e+00,3.000000e+00
C19,999999.0,1.907794e+02,2.734394e+02,3.300000e+01,3.500000e+01,3.900000e+01,2.970000e+02,1.835000e+03
C20,999999.0,4.550590e+04,4.984381e+04,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000840e+05,1.002480e+05
C21,999999.0,6.993616e+01,3.851384e+01,1.300000e+01,4.300000e+01,6.100000e+01,7.900000e+01,1.950000e+02

In [19]:
##接下来对特征进行处理，先将类别特征进行编码
#针对类型类的特征，先进行编码，编码之前构建字典
from sklearn import preprocessing

def label_encode(field,df):
    dic = []
    df_field = df[field]
    list_field = df_field.tolist()

    #构建field字典
    for i in list_field:
        if i not in dic:
            dic.append(i)

    label_field = preprocessing.LabelEncoder()
    label_field.fit(dic)

    df_field_enconde_tmp = label_field.transform(df_field)
    df_field_enconde = pd.DataFrame(df_field_enconde_tmp, index=df.index, columns=[(field+'_enconde')])
    return df_field_enconde

In [34]:
##100万数据实在跑不过来，为了演示，再做截断
df_click_1 =  df[df["click"] == 1].iloc[:10000,:]
df_click_0 =  df[df["click"] == 0].iloc[:52400,:]

#然后合并回去（行合并），作为新的df
df=pd.concat([df_click_1, df_click_0])

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62400 entries, 8 to 63476
Data columns (total 24 columns):
id                  62400 non-null float64
click               62400 non-null int64
hour                62400 non-null int64
C1                  62400 non-null int64
banner_pos          62400 non-null int64
site_id             62400 non-null object
site_domain         62400 non-null object
site_category       62400 non-null object
app_id              62400 non-null object
app_domain          62400 non-null object
app_category        62400 non-null object
device_id           62400 non-null object
device_ip           62400 non-null object
device_model        62400 non-null object
device_type         62400 non-null int64
device_conn_type    62400 non-null int64
C14                 62400 non-null int64
C15                 62400 non-null int64
C16                 62400 non-null int64
C17                 62400 non-null int64
C18                 62400 non-null int64
C19                 62400 non-null int64
C20                 62400 non-null int64
C21                 62400 non-null int64
dtypes: float64(1), int64(14), object(9)
memory usage: 11.9+ MB

In [35]:
# site_id             999999 non-null object
# site_domain         999999 non-null object
# site_category       999999 non-null object
# app_id              999999 non-null object
# app_domain          999999 non-null object
# app_category        999999 non-null object
# device_id           999999 non-null object
# device_ip           999999 non-null object
# device_model        999999 non-null object
df_site_id_enconde = label_encode('site_id',df)
df_site_domain_enconde = label_encode('site_domain',df)
df_site_category_enconde = label_encode('site_category',df)
df_app_id_enconde = label_encode('app_id',df)
df_app_domain_enconde = label_encode('app_domain',df)
df_app_category_enconde = label_encode('app_category',df)
df_device_id_enconde = label_encode('device_id',df)
df_device_ip_enconde = label_encode('device_ip',df)
df_device_model_enconde = label_encode('device_model',df)

In [40]:
#拼接特征回去
# id                  999999 non-null float64
# click               999999 non-null int64
# hour                999999 non-null int64
# C1                  999999 non-null int64
# banner_pos          999999 non-null int64
# site_id             999999 non-null object
# site_domain         999999 non-null object
# site_category       999999 non-null object
# app_id              999999 non-null object
# app_domain          999999 non-null object
# app_category        999999 non-null object
# device_id           999999 non-null object
# device_ip           999999 non-null object
# device_model        999999 non-null object
# device_type         999999 non-null int64
# device_conn_type    999999 non-null int64
# C14                 999999 non-null int64
# C15                 999999 non-null int64
# C16                 999999 non-null int64
# C17                 999999 non-null int64
# C18                 999999 non-null int64,
# C19                 999999 non-null int64
# C20                 999999 non-null int64
# C21                 999999 non-null int64
df_input = pd.concat([df[['click','banner_pos','device_type','device_conn_type'
                          ,'C1','C14','C15','C16','C17','C18','C19','C20','C21']]
                      ,df_site_id_enconde
                      ,df_site_domain_enconde
                      ,df_site_category_enconde
                      ,df_app_id_enconde
                      ,df_app_domain_enconde
                      ,df_app_category_enconde
                      ,df_device_id_enconde
                      ,df_device_ip_enconde
                      ,df_device_model_enconde], axis=1)

In [42]:
df_input.describe().T

,count,mean,std,min,25%,50%,75%,max
click,62400.0,0.160256,0.366847,0.0,0.0,0.0,0.00,1.0
banner_pos,62400.0,0.198013,0.402148,0.0,0.0,0.0,0.00,5.0
device_type,62400.0,1.059631,0.591574,0.0,1.0,1.0,1.00,5.0
device_conn_type,62400.0,0.199183,0.634956,0.0,0.0,0.0,0.00,5.0
C1,62400.0,1005.041779,1.099718,1001.0,1005.0,1005.0,1005.00,1010.0
C14,62400.0,17701.539696,3228.240792,375.0,15704.0,17654.0,20362.00,21705.0
C15,62400.0,318.395256,11.819491,120.0,320.0,320.0,320.00,728.0
C16,62400.0,56.676410,36.533532,20.0,50.0,50.0,50.00,480.0
C17,62400.0,1966.523093,393.891028,112.0,1722.0,1993.0,2307.00,2497.0
C18,62400.0,0.789439,1.226222,0.0,0.0,0.0,2.00,3.0
C19,62400.0,130.603077,241.374198,33.0,35.0,35.0,39.00,1835.0
C20,62400.0,38018.727035,48582.414092,-1.0,-1.0,-1.0,100083.00,100248.0
C21,62400.0,88.775721,45.489415,13.0,61.0,79.0,156.00,157.0
site_id_enconde,62400.0,289.941779,204.245522,0.0,88.0,268.0,404.00,760.0
site_domain_enconde,62400.0,467.118638,169.278146,0.0,389.0,492.0,619.00,646.0
site_category_enconde,62400.0,5.829038,4.456125,0.0,2.0,4.0,6.00,15.0
app_id_enconde,62400.0,523.173958,131.784304,0.0,572.0,572.0,572.00,610.0
app_domain_enconde,62400.0,20.128926,5.550983,0.0,21.0,21.0,21.00,47.0
app_category_enconde,62400.0,1.169087,3.480267,0.0,0.0,0.0,0.00,18.0
device_id_enconde,62400.0,3291.346987,603.055366,0.0,3405.0,3405.0,3405.00,5049.0
device_ip_enconde,62400.0,14718.134888,8451.461740,0.0,7638.0,14525.5,22008.25,29532.0
device_model_enconde,62400.0,1099.835000,602.001177,0.0,560.0,1148.0,1634.00,2184.0

In [46]:
from sklearn.model_selection import train_test_split
#对数据进行分割，分割为训练集和测试集
x_train,x_test,y_train,y_test = train_test_split(df_input.iloc[:,1:],df_input["click"],test_size=0.3, random_state=123)

In [48]:
##导入XGB相关的库
from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.externals import joblib

In [51]:
##进行xgboost拟合
import time 

begin_time = time.time()
print(f'Begin Time : {time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(begin_time))}')

##受限于机器的资源，这里就不做gridsearch调参了，直接凑合着来(按最小资源消耗来设置参数)
model = XGBClassifier(learning_rate=0.1
                     ,n_estimators=10
                     ,max_depth=3
                     ,objective='binary:logistic'
                     )

model.fit(x_train, y_train, eval_metric="auc")

end_time = time.time()
print(f'End Time : {time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(end_time))}')

Begin Time : 2020-04-18 10:27:44
End Time : 2020-04-18 10:27:45

In [52]:
##保存xgb的model
joblib.dump(model, './model/xgb_model.pkl')

['./model/xgb_model.pkl']

In [56]:
##效果输出函数
def func_print_score(x_data,y_data,data_type,model_x):
    y_pred = model_x.predict(x_data)
    
    print(f'==============({data_type})===================')
    confusion = metrics.confusion_matrix(y_data, y_pred)
    print(confusion)
    
    print('------------------------')
    auc = metrics.roc_auc_score(y_data,y_pred)
    print(f'AUC: {auc}')
    
    print('------------------------')
    accuracy = metrics.accuracy_score(y_data,y_pred)
    print(f'Accuracy: {accuracy}')
    
    print('------------------------')
    report = metrics.classification_report(y_data, y_pred)
    print(report) 
    
    print('=============================================')

In [57]:
func_print_score(x_test,y_test,'testdata-xgb', model)

==============(testdata-xgb)===================
[[15576   196]
 [ 2765   183]]
------------------------
AUC: 0.5248244488713144
------------------------
Accuracy: 0.8418269230769231
------------------------
             precision    recall  f1-score   support

          0       0.85      0.99      0.91     15772
          1       0.48      0.06      0.11      2948

avg / total       0.79      0.84      0.79     18720

=============================================

/data/python/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff: